// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int greater = 0;
		int smaller = 0;
		for (int count = 0; count < N; count++){
			double random = Math.random() * N;
			if (random > 0.5 * N) {
				greater ++;
			} else {
				 if (random <= 0.5 * N) {
				smaller++;
				}
		}
	}
	double greaterNew = greater;
	double smallerNew = smaller;
	double ratio = smallerNew / greaterNew;
		System.out.println("> 0.5: " + smaller + " times");
		System.out.println("<= 0.5: " + greater + " times");
		System.out.println("Ratio: " + ratio);
		}
	}

